config/routes.rb
SendFive::Application.routes.draw do

  root :to => 'pages#home'
  resources :gifts
  resources :users
  
  match "/learn_more" => "pages#learn_more"

  resources :sessions, :only => [:new, :create, :destroy]

  post "/pay_for_gift" => "gifts#pay_for_gift"

  get "send_to_paypal" => "gifts#send_to_paypal"

  match "receive_from_paypal" => "gifts#receive_from_paypal"

  match "paypal_listener" => "gifts#paypal_listener"
end

app/models/code.rb
class Code < ActiveRecord::Base

  belongs_to :vendor
  belongs_to :gift

  scope :available, where(:sent => false)

  before_save :set_assigned

  def set_assigned
    self.sent = true if self.gift_id.present?
  end

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  require 'twilio_helper'

  has_one :code
  has_one :vendor, :through => :code

  belongs_to :receiver,
             :class_name => 'User',
             :foreign_key => 'receiver_id'
  
  belongs_to :giver,
             :class_name => 'User',
             :foreign_key => 'giver_id'
  
  before_create :associate_code
  #after_create :send_texts

  def associate_code
    if vendor.nil?
      errors.add(:vendor, "is required") 
      return false
    end

    if vendor.charity?
      code = vendor.codes.build
    else
      code = Code.available.where(:vendor_id => vendor.id).first
    end

    if code.nil?
      errors.add(:vendor, "has no gifts available. Someone must have just stolen the last one!") 
      return false
    else

    end
    self.code = code
  end

  def send_texts
    if vendor.charity?
      TwilioHelper::send_text '+13132215621', receiver.phone_number, charity_text_message
   else
     TwilioHelper::send_text '+13132215621', receiver.phone_number, text_message_1
     TwilioHelper::send_text '+13132215621', receiver.phone_number, text_message_2
   end
  end

  def sender_name
    giver.first_name
  end

  def charity_text_message
    "#{sender_name} has donated $5 to #{vendor.name} in your name through SendFive! #{sender_name} says:\n #{message}"
  end

  def text_message_1
    "#{sender_name} sent you $5 to #{vendor.name} through sendfiveNOW! #{sender_name} says:\n '#{message}'"
  end

  def text_message_2
    "To redeem your gift, go to your local #{vendor.name} and present the following code:\n   -----  \n#{code.code_number}"
  end

  def paypal_url(return_url, gift_id, notify_url)
    values = {
      :business => "BRE79W46WYY6A",
      :return => return_url,
      :amount => 5,
      :shipping => 0.5,
      :currency_code => "USD",
      :item_name => "Send Five Text Message Gift",
      :cmd => "_xclick",
      :item_number => gift_id,
      :notify_url => notify_url
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

  def paypal_listener_response(params)
    "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate" + params.to_query 
  end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password
  has_many  :gifts_received,
            :class_name => Gift,
            :foreign_key => :receiver_id
  has_many :gifts_given,
            :class_name => Gift,
            :foreign_key => :giver_id
  
  before_validation :set_passwords
  
  def set_passwords
    return true if password.present? && password_confirmation.present?
    self.password = "test"
    self.password_confirmation = "test"
  end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  has_many :codes

  def self.available
    vendors = Code.available.collect { |code| code.vendor }
    return vendors.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

  def new
    if params[:vendor].present?
      @gift = Gift.new
    else
      @vendors = Vendor.available  
    end  

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    phone_number = "+1" + params[:receiver][:area_code] + params[:receiver][:phone_number1] + params[:receiver][:phone_number2]
    @receiver = User.find_by_phone_number(phone_number)
    #    @receiver = User.find_by_phone_number(params[:receiver][:phone_number])
    if @receiver.nil?
      @receiver = User.new
      @receiver.phone_number = phone_number
      @receiver.first_name = params[:receiver][:first_name]
      @receiver.save
    end

    @giver = User.create(params[:giver])

    @gift = Gift.new params[:gift]

    @gift.vendor = Vendor.find(params[:vendor][:id])
    @gift.receiver = @receiver
    @gift.giver = @giver

    if @gift.save
      redirect_to gift_path(@gift)
    else
      @vendors = Vendor.available
      render :new
    end
  end
  
  def show
    @gift = Gift.find(params[:id].to_i)
  end

  def pay_for_gift
    @gift = Gift.find(params[:id])
    token = params[:stripeToken]
    Stripe.api_key = ENV['stripe_api_key']
    charge = Stripe::Charge.create(
      :amount => 599, # amount in cents, again
      :currency => "usd",
      :card => token,
      :description => @gift.id
    )
    @gift.send_texts 
    redirect_to new_user_url
  end

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def learn_more
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user.save && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have logged in."
      redirect_to user_url(session[:user_id])
    else
        flash[:notice] = "Please try again!"
        redirect_to new_session_url
    end
  end
  
  def destroy
    reset_session
    flash[:notice] = "You have logged out."
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(params[:user])
    session[:user_id] = @user.id
    redirect_to user_url(@user)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def stylesheets(*files)
    content_for(:head) { stylesheet_link_tag(*files) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gifts/_text_message_form.html.haml
= form_for(@gift) do |form|
  - unless @gift.errors.empty?
    %h3 There was a problem with the form
    %ul
      - @gift.errors.full_messages.each do |error|
        %li= error
  From: 
  .inputs= text_field :giver, :first_name, :placeholder => "Johnny Appleseed"
  %br
  To:
  .inputs
    = text_field :receiver, :first_name, :placeholder => "Betty"
  %br
  Phone Number:
  .inputs
    = text_field :receiver, :area_code, :placeholder => "123", :class => 'inline', :maxlength => 3 
    = text_field :receiver, :phone_number1, :placeholder => "234", :class => 'inline', :maxlength => 3
    = text_field :receiver, :phone_number2, :placeholder => "3456", :class => 'inline', :maxlength => 4
  %br
  = form.label "Message:" 
  %span#text_char_count 160 characters left
  .inputs
    = form.text_area :message, :placeholder => "Happy Birthday, Cookie. Go buy yourself a cup of coffee on me. Talk soon!"
  %br
  = hidden_field :vendor, :id, :value => params[:vendor][:id]
  = form.submit "Preview Message", :class => 'previewbutton right'
  .clr

app/views/gifts/_vendor_button.html.haml
= link_to vendor.name, nil, :id => "button_#{vendor.id}", :class => 'button vendor_button'

app/views/gifts/_vendor_form.html.haml
= form_tag(new_gift_path, :method => "get", :remote => true, :id => "vendor_form") do 
  = hidden_field :vendor, :id
  - @vendors.each do |vendor|
    = render 'vendor_button', :vendor => vendor

app/views/gifts/new.html.haml
= stylesheets('gifts')
#gift_form_container
  - if params[:vendor].present?
    .instructions
      Choose what gift you would like to send
    = render 'text_message_form'	
  - else
    - if @vendors.present?
      .instructions
        Choose what gift you would like to send
      = render 'vendor_form'
    - else
      .instructions
        We're sorry. We've been making too many people smile and are out of gift codes. Check back soon!

app/views/gifts/new.js.erb
$("#gift_form_container").fadeOut("fast", function() {
  $("#gift_form_container").html("<%= escape_javascript(render('text_message_form')) %>");
  $("#gift_form_container").fadeIn("slow");
});

app/views/gifts/show.html.erb
<%= stylesheets('gifts') %>
<div id="sign_up_thanks">
  <h1 >Preview your message, pay, and send now!</h1>
</div>
<br/>
<div id="gift_form_container">
  From: 
    <div class="show">
      <%= @gift.giver.first_name %>
    </div>
  To:  
    <div class="show">
      <%= @gift.receiver.first_name %>
      at
      <%= @gift.receiver.phone_number %>
    </div>
  Message: 
    <div class="show">
      <% if @gift.vendor.charity %> 
        <%= @gift.charity_text_message %>
      <% else %>
        <%= @gift.text_message_1 %></br></br>
        <%= @gift.text_message_2 %>
      <% end %>
    </div>

    <br/>

    <div id="payment_form">
      <div id="payment_summary">
        <div id="summary_price">Gift Card: $5.00</div>
        <div id="summary_fee">Fee: $0.99</div>
        <div id="summary_total">Total: $5.99</div>
      </div>
      
      <div class="payment-errors"></div>
      <div id="payment_details">
        <%= form_tag pay_for_gift_url, :id => "payment-form" do %>

          <%= hidden_field_tag :id, @gift.id %>
         
          <div id="payment_details_email"><%= text_field_tag :email, nil, :placeholder => 'Your Email', :size => 30 %></div>

          <div id="payment_details_card_number"><%= text_field_tag :card_number, nil, :name => nil, :placeholder => "Credit Card Number", :maxlength => 16, :size => 20 %></div>

          <div id="payment_details_CVV"><%= text_field_tag :card_code, nil, :name => nil, :placeholder => "CVV", :class => 'inline', :size => 4, :maxlength => 4 %></div>

          <div id="card_images"><%= image_tag("creditcards.png") %></div>
          
          <div id="payment_details_expiration"><%= label_tag :card_expiration, "Expires On:" %>
            <%= select_month nil, {:add_month_numbers => true}, {:name => nil, :id => "card_month"} %>
            <%= select_year nil, {:start_year => Date.today.year, :end_year => Date.today.year+15}, {:name => nil, :id => "card_year"} %>
          </div>
      </div>
              <%= submit_tag "Pay and Send Text!", :id => "pay-button" %>

      <% end %>
   </div>  
  </div>

app/views/layouts/_authentication.html.erb
<!--
<div id="top_navigation">
  <% if session[:user_id].present? %>
    <%= link_to "My Account", user_url(session[:user_id]) %> | <%= link_to "Sign Out", session_url(session[:user_id]), :method => "delete" %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
  <% end %>
</div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SendFiveNow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic', :media => 'screen' %>
  <%= yield(:head) %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <script type="text/javascript">
    // this identifies your website in the createToken call below
    Stripe.setPublishableKey('pk_RbRFD3om78PVOduOlqSTnDEEEk1ab');
  </script>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-26996682-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
  <div id=home_banner>
    <div id="header">
      <div class="content_wrapper">
        <div id="logo">
          <span class = "first">sendfive</span><span class="second">now</span>
        </div>
        <%= render 'layouts/authentication' %>
        <br class="clr"/>
      </div>
    </div>
  </div>
  <div class="clr"></div>
    <div id="main_content" class="content_wrapper">
      <%= yield %>
    </div>
</body>
</html>

app/views/pages/home.html.haml
= stylesheets('pages')
.home_page_image_container
  .phone_image_wrapper
    = image_tag 'home_iphone.png', :class => "home_iphone"
  .actions_wrapper
    %h1#purpose SMS a $5 Gift Instantly
    %h2#tagline make someone smile today
    #send_five_now_wrapper= link_to 'Send $5 Now', new_gift_path
    #learn_more_wrapper= link_to "Learn More", "/learn_more", :id => 'learn_more'

.clr

app/views/pages/learn_more.html.erb
<%= stylesheets('pages') %>
<div id="learn_more_top">sendfiveNow allows you to send an SMS message to your friends and family with $5 gift codes to local and national retailers or $5 donations to charities. Buy your friend a beer on his birthday, say hello to your Mom with a cup of coffee, or donate $5 in your little brother's name to a charity. Make someone's day with a hello and an unexpected $5 gift in three easy steps.
  <br/>
  <br/>
  <div id="send_five_now_wrapper"><%=  link_to 'Send $5 Now', new_gift_path %></div>
</div>

<div id="column_wrapper">
  <div id="one" class="column">
    <h1>Choose what to send.</h1>
    <div class="column_text">Select from our list of merchants. You can send a $5 gift code redeemable at bars, cafes, and restaurants or decide to send $5 to several charities.</div>
  </div>
  <div id="two" class="column">
    <h1>Tell us who to Send Five to.</h1>
    <div class="column_text">Enter the name and SMS eligible phone number of whomever you'd like to send five to. You can even customize the message to say whatever you'd like. Happy Birthday, Thanks, Good Luck! It's that simple.</div>
  </div>
  <div id="three" class="column">
    <h1>Pay and send your gift.</h1>
    <div class="column_text">Upon payment we'll send your message to the recipient with the redemption code. You'll make someone's day and deposit some good karma into the bank.</div>
  </div>
  <div class="clr"></div>
</div>



<!-- <div id="one">
  1. Choose What to Send.</br>
  <p>Select from our list of merchants. You can send a $5 gift code redeemable at bars, cafes, and restaurants or decide to send $5 to several charities.</p>
</div>

<div id="three">
  3. Pay and Send Your Gift.</br>
  <p>Pay through PayPal. Upon payment we'll send your message to the recipient with the redemption code. You'll make someone's day and deposit some good karma into the bank.</p>
</div>

<div id="two">
  2. Tell Us Who to Send Five To</br>
  <p>Enter the name and SMS eligible phone number of whomever you'd like to send five to. You can even customize the message to say whatever you'd like. Happy Birthday, Thanks, Good Luck! It's that simple.</p> 
</div> -->
  
  

app/views/users/_form.html.erb
<br>
<%= form_for(@user) do |f| %>

<%= f.label "Name"%>
<div class="inputs">
  <%= f.text_field :first_name, :placeholder => "First" %>
  <%= f.text_field :last_name, :placeholder => "Last"%>
</div>


<%= f.label :phone_number %>
<div class="inputs"><%= f.text_field :phone_number, :placeholder => '+14448887722' %></div>

<%= f.label :email %>
<div class="inputs"><%= f.text_field :email, :placeholder => "cookie@monster.com" %></div>

<%= f.label :password %>
<div class="inputs"><%= f.text_field :password %></div>

<%= f.label :password_confirmation %>
<div class="inputs"><%= f.text_field :password_confirmation %></div>

<%= f.submit "Create Account",:id => "create_account",  :class => "previewbutton" %>

<% end %>

app/views/users/new.html.erb
<%= stylesheets('gifts') %>
<div id="sign_up_thanks">
  <h1 >Success! You've just made someone smile.</h1>
</div>
<br>
<div class="instructions">  
  <h2>Now go tell three friends, two family members, and one enemy about SendFiveNow.</h2>
</div>  
<hr>
<!--
<br>
<div class="instructions">
  Now sign up for an account and send $5 to the rest of your friends and family.
</div>
</br>

<div id="gift_form_container">
  <%= render 'form'%>
</div>
-->

app/views/users/show.html.erb
Hello, <%= @user.first_name %>! </br>

You've sent: x gifts